default :
  Input :
    Discovery dataset name : "Carcinoma"
    Recovery dataset name : "visium_6723_1"
    Input Visium directory : "example_data/visium_6723/6723_KL_1"
    #Path to a file containing the precomputed cell fractions for the visium array
    Recovery cell type fractions : "NULL" 
    Malignant cell of origin : "Epithelial.cells"
    CIBERSORTx username : "cody.n.heiser@vanderbilt.edu"
    CIBERSORTx token : "f3237c79cd99c96a971e7e8f27b36d97"

  Output :
    Output folder : "VisiumOutput"

  Pipeline settings :
    Number of threads : 10
