default :
  Input :
    Discovery dataset name : "discovery_scRNA_COLONMAP_500"
    Recovery dataset name : "visium_6723_1"
    Input Visium directory : "example_data/visium_6723/6723_KL_1"
    #Path to a file containing the precomputed cell fractions for the visium array
    Recovery cell type fractions : "CIBERSORTx/fractions/visium/visium_6723_1/CIBERSORTx_Results_6723_1.txt"
    Malignant cell of origin : "MSS_1"
    CIBERSORTx username : "cody.n.heiser@vanderbilt.edu"
    CIBERSORTx token : "f3237c79cd99c96a971e7e8f27b36d97"

  Output :
    Output folder : "VisiumOutput"

  Pipeline settings :
    Number of threads : 12
