default :
  Input :
    Discovery dataset name : "discovery_scRNA_COLONMAP+"
    Expression matrix : "example_data/COLONMAP+_discovery_data.txt"
    Annotation file : "example_data/COLONMAP+_discovery_annotation.txt"
    Annotation file column to scale by : NULL
    Annotation file column(s) to plot : []

  Output :
    Output folder : "DiscoveryOutput_scRNA_COLONMAP+"

  Pipeline settings :
    #Pipeline steps:
    #   step 1 (extract cell type specific genes)
    #   step 2 (cell state discovery on correlation matrices)
    #   step 3 (choosing the number of cell states)
    #   step 4 (extracting cell state information)
    #   step 5 (cell state re-discovery in expression matrices)
    #   step 6 (extracting information for re-discovered cell states)
    #   step 7 (cell state QC filter)
    #   step 8 (ecotype discovery)
    Pipeline steps to skip : [1,2,3,4,5,6,7]
    Filter non cell type specific genes : True
    Number of threads : 12
    Number of NMF restarts : 10
    Maximum number of states per cell type : 18
    Cophenetic coefficient cutoff : 0.96
